default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  host: localhost
  port: 49543
  database: activiti_schedulr_development
  username: postgres
  password: postgres

test:
  <<: *default
  host: localhost
  port: 49543
  database: activiti_schedulr_test
  username: postgres
  password: postgres

production:
  <<: *default
  host: localhost
  database: activiti_schedulr_production
  username: postgres
  password: postgres
